## Loading libraries and the model

In [1]:
import pandas as pd

from cobra.io import read_sbml_model
from pathlib import Path

In [ ]:
# the XML and Excel files can be sourced from: doi: 10.1186/s12859-019-2844-z

path = Path("rpal.xml")
model = read_sbml_model(str(path.resolve()))

mdetails = pd.read_excel('modelDetails.xlsx', sheet_name='Reactions')

Model does not contain SBML fbc package information.
SBML package 'layout' not supported by cobrapy, information is not parsed
SBML package 'render' not supported by cobrapy, information is not parsed
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00234 "10-Formyltetrahydrofolate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C15606 "1,2-dihydroxy-3-keto-5-methylthiopentene">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00641DA "1,2-Diacyl-sn-glycerol (Dark Aerobic)">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00641LN "1,2-Diacyl-sn-glycerol (Light Anaerobic)">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C04092 "1,2-Didehydropiperidine-2-carboxylate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C05758 "trans-Dodec-2-enoyl-[acp]">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C03012 "1,2-Naphthalenediol">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00986 "1,3-Propanediamine">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00236 "3-Phospho-D-glyceroylphosphate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C11829 "13(1)-Hydroxy-magnesium-protoporphyrinIX13-monomethylester">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C05421 "15-cis-Phytoene">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C03203 "1-Hydroxy-2-naphthoate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C03912 "(S)-1-Pyrroline-5-carboxylate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C03340 "L-2,3-Dihydrodipicolinate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C06007 "(R)-2,3-Dihydroxy-3-methylpentanoate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C02923 "2,3-Dihydroxytoluene">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C03283 "L-2,4-Diaminobutyrate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C05923 "2,5-Diaminopyrimidine nucleoside triphosphate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C06148 "2,5-Diamino-6-(5'-triphosphoryl-3',4'-trihydroxy-2'-oxopentyl)-">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C01304 "2,5-Diamino-6-(5'-phosphoribosylamino)-4-pyrimidineone">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00666 "LL-2,6-Diaminoheptanedioate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00680 "meso-2,6-Diaminoheptanedioate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C04807 "2-Amino-7,8-dihydro-4-hydroxy-6-(diphosphooxymethyl)pteridine">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C06006 "(S)-2-Aceto-2-hydroxybutanoate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C01300 "2-Amino-4-hydroxy-6-hydroxymethyl-7,8-dihydropteridine">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C03508 "L-2-Amino-3-oxobutanoicacid">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C01278 "2-Carboxy-2,5-dihydro-5-oxofuran-2-acetate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C01302 "1-(2-Carboxyphenylamino)-1-deoxy-D-ribulose5-phosphate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C04691 "2-Dehydro-3-deoxy-D-arabino-heptonate7-phosphate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00966 "2-Dehydropantoate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00672 "2-Deoxy-D-ribose1-phosphate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00673 "2-Deoxy-D-ribose5-phosphate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C16468 "(2E)-5-Methylhexa-2,4-dienoyl-CoA">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C01146 "2-Hydroxy-3-oxopropanoate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C04324 "2-Hydroxy-4-carboxyhexa-2,4-dienedioate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C09812 "2-Hydroxycyclohexane-1-carboxyl-CoA">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C05375 "2-Hydroxy-2-hydropyrone-4,6-dicarboxylate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C05852 "2-Hydroxyphenylacetate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C02631 "2-Isopropylmaleate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C01180 "4-Methylthio-2-oxobutanoicacid">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C03344 "2-Methylacetoacetyl-CoA">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C04752 "2-Methyl-4-amino-5-hydroxymethylpyrimidinediphosphate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C01251 "(R)-2-Hydroxybutane-1,2,4-tricarboxylate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C11434 "2-C-Methyl-D-erythritol4-phosphate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C11453 "2-C-Methyl-D-erythritol2,4-cyclodiphosphate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C02226 "Citraconate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00349 "2-Methyl-3-oxopropanoate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00109 "2-Oxobutanoate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C09813 "2-Oxocyclohexane-1-carbonyl-CoA">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C03063 "2-Oxohept-3-enedioate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C05811 "2-Octaprenyl-6-hydroxyphenol">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C05813 "2-Octaprenyl-6-methoxy-1,4-benzoquinone">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C05815 "2-Octaprenyl-3-methyl-5-hydroxy-6-methoxy-1,4-benzoquinone">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C05814 "2-Octaprenyl-3-methyl-6-methoxy-1,4-benzoquinone">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C05812 "2-Octaprenyl-6-methoxyphenol">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C05810 "2-Octaprenylphenol">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C03586 "2-Oxo-2,3-dihydrofuran-5-acetate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00322 "2-Oxoadipate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C03671 "2-Pyrone-4,6-dicarboxylate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C11436 "2-Phospho-4-(cytidine5'-diphospho)-2-C-methyl-D-erythritol">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00631 "2-Phospho-D-glycerate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00988 "2-Phosphoglycolate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C03221 "2-trans-Dodecenoyl-CoA">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C05125 "2-(alpha-Hydroxyethyl)thiaminediphosphate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C15888 "3,4,3',4'-Tetrahydrospirilloxanthin">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C15886 "3,4-Dihydroanhydrorhodovibrin">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00230 "3,4-Dihydroxybenzoate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C15887 "3',4'-Dihydrorhodovibrin">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C15874 "3,4-Dehydrorhodopin">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C01179 "3-(4-Hydroxyphenyl)pyruvate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C01142 "(3S)-3,6-Diaminohexanoate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C11638 "3-Amino-2-oxopropylphosphate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C05145 "3-Aminoisobutyricacid">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C04411 "(2R,3S)-3-Isopropylmalate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C02504 "(2S)-2-Isopropylmalate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C04236 "(2S)-2-Isopropyl-3-oxosuccinate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C05381 "3-Carboxy-1-hydroxypropyl-ThPP">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00944 "3-Dehydroquinate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C02637 "3-Dehydroshikimate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C04675 "3-Hydroxy-3-(4-methylpent-3-en-1-yl)glutaryl-CoA">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C16469 "3-Hydroxy-5-methylhex-4-enoyl-CoA">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C16220 "3-Hydroxyoctadecanoyl-[acp]">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C06001 "(S)-3-Hydroxyisobutyrate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C04688 "(3R)-3-Hydroxytetradecanoyl-[acyl-carrierprotein]">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C04405 "(2S,3S)-3-Hydroxy-2-methylbutanoyl-CoA">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C05668 "3-Hydroxypropionyl-CoA">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C04181 "2-Oxo-3-hydroxyisovalerate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C14145 "(3S)-3-Hydroxyadipyl-CoA">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C03069 "3-Methylcrotonyl-CoA">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C02939 "3-Methylbutanoyl-CoA">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C03231 "3-Methylglutaconyl-CoA">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00141 "3-Methyl-2-oxobutanoicacid">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00671 "(S)-3-Methyl-2-oxopentanoicacid">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C14088 "3-Methylsalicylate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C05759 "3-Oxotetradecanoyl-[acp]">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C05753 "3-Oxodecanoyl-[acp]">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C18153 "3-Hydroxyethylbacteriochlorophyllidea">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C05746 "3-Oxohexanoyl-[acp]">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C06714 "3-Hydroxypimelyl-CoA">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C01013 "3-Hydroxypropanoate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C05750 "3-Oxooctanoyl-[acp]">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C05809 "3-Octaprenyl-4-hydroxybenzoate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C02232 "3-Oxoadipyl-CoA">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C05265 "3-Oxodecanoyl-CoA">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C05263 "3-Oxododecanoyl-CoA">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C05269 "3-Oxohexanoyl-CoA">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C16219 "3-Oxostearoyl-[acp]">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C05267 "3-Oxooctanoyl-CoA">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C05259 "3-Oxopalmitoyl-CoA">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C05261 "3-Oxotetradecanoyl-CoA">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00197 "3-Phospho-D-glycerate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C03232 "3-Phosphonooxypyruvate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C01269 "5-O-(1-Carboxyvinyl)-3-phosphoshikimate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C05100 "3-Ureidoisobutyrate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C02642 "3-Ureidopropionate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00334 "4-Aminobutanoate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00555 "4-Aminobutyraldehyde">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00568 "4-Aminobenzoate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C11355 "4-Amino-4-deoxychorismate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C01279 "4-Amino-5-hydroxymethyl-2-methylpyrimidine">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C04556 "4-Amino-2-methyl-5-phosphomethylpyrimidine">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C04434 "4-Carboxy-2-hydroxyhexa-2,4-dienedioate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C04484 "4-Carboxy-2-hydroxymuconate semialdehyde">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C11435 "4-(Cytidine5'-diphospho)-2-C-methyl-D-erythritol">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C04115 "4-Carboxy-4-hydroxy-2-oxoadipate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00811 "4-Coumarate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00811PX "4-Coumarate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00811_b "4-Coumarate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00811XT "4-Coumarate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C01468 "4-Cresol">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C03078 "4-Guanidinobutanamide">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C01035 "4-Guanidinobutanoate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00633 "p-Hydroxybenzaldehyde">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C02949 "4-Hydroxybenzoyl-CoA">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00156 "4-Hydroxybenzoate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00156PX "4-Hydroxybenzoate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00156_b "4-Hydroxybenzoate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species XC279 "4-Hydroxybenzylalcohol">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00156XT "4-Hydroxybenzoate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C05938 "L-4-Hydroxyglutamatesemialdehyde">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C14110 "4-Hydroxymethylcatechol">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C14109 "4-Hydroxymethylsalicylate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C06056 "4-Hydroxy-L-threonine">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C06730 "4-Methylcatechol">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00233 "4-Methyl-2-oxopentanoate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C04327 "4-Methyl-5-(2-phosphoethyl)-thiazole">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C14103 "4-Methylsalicylate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00870 "4-Nitrophenol">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C03360 "4-Nitrophenyl phosphate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C03082 "4-Phospho-L-aspartate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C03393 "4-Phospho-D-erythronate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C03492 "D-4'-Phosphopantothenate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C04732 "5-Amino-6-(1-D-ribitylamino)uracil">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C04051 "5-Amino-4-imidazolecarboxyamide">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C00430 "5-Aminolevulinate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C04454 "5-Amino-6-(5'-phosphoribitylamino)uracil">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C01268 "5-Amino-6-(5'-phosphoribosylamino)uracil">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C03479 "5-Formyltetrahydrofolate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species C11821 "5-Hydroxyisourate">

## Model setup
Setting flux bounds for certain relevant reactions

In [3]:
# Setting acetate uptake rate to 0
model.reactions.XR57.bounds = (0, 0) # acetate

# CO2 import/export bounds
model.reactions.XR72.bounds = (0, 0)
model.reactions.XR73.bounds = (0, 1000)

# Permitting metabolite efflux for acetate
model.reactions.XR59.bounds = (0, 100)

# Setting coumarate uptake rate to Janusian conditions (immediately preceding maximal growth rate)
model.reactions.XR242.bounds = (0.29, 0.29)

Solving the system

In [4]:
solution = model.optimize()

## Model analysis

Code to identify the reactions a certain metabolite is involved in:

In [5]:
model.metabolites.C00074.summary()

Code to pull details about a given reaction, and return the flux through a reaction:

In [8]:
model.reactions.R00658

In [9]:
model.reactions.R00658.flux

-0.07536819841734493